name: Automatic Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome
        run: echo Start deploying Sen API
      - name: Deploy node to Render
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
